[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "vibrationdb"
version = "0.0.0"
description = "Vibration database tools"
requires-python = ">=3.9"

[tool.setuptools]
packages = ["vibtool"]
